INSERT INTO tbl_cards (hp, name, info, attack, dammage, weak, resistence, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(120, 'Charizard', 'Flame Pokémon', 'Fire Spin', '100', 'Water', 'Grass', '3', 4, 1, 1, 3),
(60, 'Pikachu', 'Mouse Pokémon', 'Thunder Jolt', '30', 'Fighting', 'Steel', '1', 58, 1, 4, 1),
(90, 'Gyarados', 'Atrocious Pokémon', 'Dragon Rage', '50', 'Electric', 'Fire', '3', 6, 1, 2, 3),
(70, 'Scyther', 'Mantis Pokémon', 'Slash', '30', 'Fire', 'Fighting', '1', 10, 2, 3, 1),
(100, 'Hitmonlee', 'Kicking Pokémon', 'Stretch Kick', '50', 'Psychic', 'None', '2', 7, 3, 6, 1),
(80, 'Bulbasaur', 'Seed Pokémon', 'Vine Whip', '20', 'Fire', 'Water', '1', 44, 1, 3, 1),
(70, 'Ivysaur', 'Seed Pokémon', 'Razor Leaf', '30', 'Fire', 'Water', '2', 2, 1, 3, 2),
(100, 'Venusaur', 'Seed Pokémon', 'Solar Beam', '60', 'Fire', 'Water', '3', 15, 1, 3, 3),
(50, 'Squirtle', 'Tiny Turtle Pokémon', 'Bubble', '10', 'Electric', 'Fire', '1', 7, 1, 2, 1),
(70, 'Wartortle', 'Turtle Pokémon', 'Water Gun', '30', 'Electric', 'Fire', '2', 42, 1, 2, 2),
(100, 'Blastoise', 'Shellfish Pokémon', 'Hydro Pump', '60', 'Electric', 'Fire', '3', 2, 1, 2, 3),
(40, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', 'Water', '1', 45, 1, 3, 1),
(60, 'Metapod', 'Cocoon Pokémon', 'Stiffen', '20', 'Fire', 'Water', '2', 11, 1, 3, 2),
(80, 'Butterfree', 'Butterfly Pokémon', 'Whirlwind', '30', 'Fire', 'Fighting', '1', 3, 1, 3, 3),
(50, 'Abra', 'Psi Pokémon', 'Psyshock', '10', 'Psychic', 'None', '1', 43, 1, 5, 1),
(70, 'Kadabra', 'Psi Pokémon', 'Recover', '30', 'Psychic', 'None', '2', 32, 1, 5, 2),
(100, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '50', 'Psychic', 'None', '3', 1, 1, 5, 3),
(60, 'Machop', 'Superpower Pokémon', 'Low Kick', '20', 'Psychic', 'None', '1', 52, 1, 6, 1),
(80, 'Machoke', 'Superpower Pokémon', 'Karate Chop', '40', 'Psychic', 'None', '2', 34, 1, 6, 2),
(100, 'Machamp', 'Superpower Pokémon', 'Seismic Toss', '60', 'Psychic', 'None', '3', 8, 1, 6, 3);
